spring:
  application:
    name: auth-server
  security:
    oauth2:
      authorizationserver:
        issuer-url: http://localhost:${server.port}/
        introspection-endpoint: /oauth2/token-info
      client:
        registration:
          github:
            client-id: ${GITHUB_OAUTH_CLIENT_ID}
            client-secret: ${GITHUB_OAUTH_CLIENT_SECRET}
          google:
            client-id: ${GOOGLE_OAUTH_CLIENT_ID}
            client-secret: ${GOOGLE_OAUTH_CLIENT_SECRET}

server:
  port: ${SERVER_PORT}

logging:
  level:
    root: DEBUG
    org.apache.tomcat.util.net.NioEndpoint: ERROR
    sun.rmi: ERROR
    java.io: ERROR
    javax.management: ERROR

cors:
  origins: http://127.0.0.1:8080,http://localhost:8080